name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: cdtest-406103
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t gcr.io/cdtest-406103/moneymind:latest .

      - name: Configure Docker and push image to GCR
        run: |
          gcloud auth configure-docker --quiet
          docker push gcr.io/cdtest-406103/moneymind:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy moneymind-service \
            --image=gcr.io/cdtest-406103/moneymind:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
