name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCLOUD_AUTH }}

      - name: Build and push Docker image to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: asia-southeast1-docker.pkg.dev/skilful-bearing-417410/moneymind/unit_testing:latest
