name: Build and Push Docker Image to GAR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: skilful-bearing-417410
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/skilful-bearing-417410/moneymind/unit_testing:latest .

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/skilful-bearing-417410/moneymind/unit_testing:latest
