name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0 # Use official setup action
        with:
          project_id: cdtest-406103
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t nodejs-sample-image .

     # - name: Configure Docker and push image
      #  run: |
       #   gcloud auth configure-docker --quiet # Use `gcloud` directly, as it's now in PATH
        #  docker tag nodejs-sample-image gcr.io/cdtest-406103/nodejs-sample-image
         # docker push gcr.io/cdtest-406103/nodejs-sample-image


       - name: Configure Docker and push image
        run: |
          ./google-cloud-sdk/bin/gcloud auth configure-docker
          docker tag nodejs-sample-image gcr.io/cdtest-406103/nodejs-sample-image
          docker push gcr.io/cdtest-406103/nodejs-sample-image


      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy nodejs-sample-service \
            --image=gcr.io/cdtest-406103/nodejs-sample-image \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
