name: Build and Push to Google Artifact Registry

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Use the latest version of the checkout action to fetch the code.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCLOUD_AUTH }}
          # Ensure GCLOUD_AUTH secret contains the entire JSON key for your Google Cloud service account.

      - name: Build and push Docker image to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: asia-southeast1-docker.pkg.dev/skilful-bearing-417410/moneymind/moneymind:latest
          # Replace ./Dockerfile with the path to your Dockerfile if necessary.
