name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: skilful-bearing-417410
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Authenticate Docker with GCR
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-southeast1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/skilful-bearing-417410/moneymind/app:latest .

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push asia-southeast1-docker.pkg.dev/skilful-bearing-417410/moneymind/app:latest
