name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Specifies that the action should only run on pushes to the main branch.

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: asia-southeast1-docker.pkg.dev  # Specifies your Artifact Registry location.
          username: _json_key
          password: ${{ secrets.GCLOUD_AUTH }}  # Uses the service account key stored in GitHub secrets.

      - name: Build and push Docker image to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: .  # Specifies the build context.
          file: ./Dockerfile  # Path to your Dockerfile, adjust if necessary.
          push: true
          tags: asia-southeast1-docker.pkg.dev/skilful-bearing-417410/moneymind/unit_testing:latest  # Full path for the image in GAR.
