name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t moneymind .
          # Replace 'moneymind' with your desired image name

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.NIcole5959__ }} | docker login -u ${{ secrets.yangyalinicole }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag moneymind ${{ secrets.yangyalinicole }}/moneymind:latest
          docker push ${{ secrets.yangyalinicole }}/moneymind:latest
          # Replace 'moneymind' with your desired image name

secrets:
  DOCKER_USERNAME:
    value: yangyalinicole
  DOCKER_PASSWORD:
    value: NIcole5959__
